#!/bin/bash

#SBATCH --job-name climate
#SBATCH --nodes 1
#SBATCH --gres gpu:A100:1
#SBATCH --mem 22G
#SBATCH --partition cnu
#SBATCH --account COSC020762
#SBATCH --output slurm_train.out
#SBATCH --exclude bp1-gpu031,bp1-gpu032

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
echo GPU number: $CUDA_VISIBLE_DEVICES

#! Run the executable
python3 -u train.py